name: PULLTEST

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script at pull_request
      run: Pull the project now !
